### PR TITLE
remove support for import.meta.resolve

### PR DESCRIPTION
**Pull request by iambumblehead**
closes https://github.com/iambumblehead/esmock/issues/234

removes support for import.meta.resolve

### CODE REVIEW

**Comment by iambumblehead** [comment]
```diff
diff --git a/src/esmockLoader.js b/src/esmockLoader.js
index 05075c1..d629eb8 100644
--- a/src/esmockLoader.js
+++ b/src/esmockLoader.js
@@ -148,11 +148,13 @@ const load = async (url, context, nextLoad) => {
         ? `const {${importedNames}} = require('${specifier}');`
         : `import {${importedNames}} from '${specifier}';`
 
-      return {
-        format: nextLoadRes.format,
-        shortCircuit: true,
-        responseURL: encodeURI(url),
-        source: hbang + importexpr + sourcesafe
+      if (nextLoadRes.format !== 'commonjs') {
+        return {
+          format: nextLoadRes.format,
+          shortCircuit: true,
+          responseURL: encodeURI(url),
+          source: hbang + importexpr + sourcesafe
+        }
       }
     }
   }
```

node v20.6 is having issues resolving some CJS modules

**Comment by iambumblehead** [comment]
The situation resolved by the above diff occurs when 'nextLoad' returns a `source` property that is defined `null`. I don't understand the circumstances which cause this.
```javascript
const nextLoadRes = await nextLoad(url, context)
console.log('nextLoadRes', nextLoadRes)
// nextLoadRes [Object: null prototype] {
//   format: 'commonjs',
//   responseURL: 'file:///home/bumble/software/esmock/tests/node_modules/map-obj/index.js?esmkgdefs=file:///import?esmkTreeId=1&esmkModuleId=import&isfound=false&isesm=false&exportNames=console',
//   source: null
// }

```

**Comment by iambumblehead** [comment]
Current status: nextLoad returns `{ source: null }` for CJS modules in node v20.6

It would take some time to try and make a reproduction test.

**Comment by iambumblehead** [comment]
for the failing mixed esm/cjs global import test, I am so far unable to resolve the issue or simplify to anything something smaller.

**Review by koshic — APPROVED** [review]

**Pull request merged**
