### PR TITLE
Remove isesm

### PR DESCRIPTION
**Pull request by iambumblehead**

### CODE REVIEW

**Comment by iambumblehead** [comment]
v12 and v14 runtimes fail, v16 and v18 pass.

**Comment by Swivelgames** [comment]
Just curious. Does the last commit here drop support for the [current `lts` version](https://nodejs.org/en/about/releases/) of Node? :slightly_smiling_face:

**Comment by iambumblehead** [comment]
@Swivelgames it would remove support. Maybe this branch should be closed. I've made a lot of noise in this thread here: https://github.com/iambumblehead/esmock/issues/48#issuecomment-1188573100

The current version of esmock is stable for regular esm javascript mocking, but the newest versions of node might make it possible to chain esmock with another loader in order to support typescript or other things. I'm trying to figure out if esmock would need to be changed in order to support that and, if so, how extensive would the changes need to be? what order should the changes be made in? etc

**Comment by iambumblehead** [comment]
@Swivelgames I didn't expect the tests here to fail for older versions of node or I might not have pushed this branch up at all

**Comment by Swivelgames** [comment]
Hmmmm... Bummer! This will definitely prove to be a difficult problem to solve. It has the potential to get really messy, especially with backwards compatibility.

I noticed the loader chaining as well a few days ago, and figured that was going to introduce some backwards compatibility complexity.

**Pull request closed without merging**
