### PR TITLE
Added NPX and ESMock (self) as a devDependency

### PR DESCRIPTION
**Pull request by Swivelgames**
I'm not sure if these changes are desired at all. If they're not, feel free to close!

### 1. :heavy_check_mark: I updated `"scripts"` in the `package.json` to use [`npx`](https://docs.npmjs.com/cli/v8/commands/npx)

The main justification for this was that I didn't have `ava`, `uvu`, or `eslint` manually installed globally. I added `npx`, since it leverages the executables that are installed in the project's local `node_modules`.

### 2. :heavy_check_mark: I added `esmock` to `devDependencies`

This allows us to specify `--loader` as `esmock`, rather than linking directly to the loader file. This better simulates a real-world use-case with our tests.

### 3. :x: Consider adding `package-lock.json` to the repo

```diff
+ It is highly recommended you commit the generated package lock to
+ source control: this will allow anyone else on your team, your
+ deployments, your CI/continuous integration, and anyone else who
+ runs npm install in your package source to get the exact same
+ dependency tree that you were developing on.

  Additionally, the diffs from these changes are human-readable
  and will inform you of any changes npm has made to your
  node_modules, so you can notice if any transitive dependencies
  were updated, hoisted, etc.
```

If you'd like, I can remove it from the `.gitignore` and add it to the repo in this PR! :slightly_smiling_face: 

## Thoroughly tested

Tested locally using:

```
git clean -dxf
npm i
npm run test-ava
npm run test-uvu
npm run lint
```

All of the above were repeated for each of the following versions of `node`:

 - [x] Node v14.120.0
 - [x] Node v15.14.0
 - [x] Node v16.16.0 _**`lts`**_
 - [x] Node v17.9.1
 - [ ] Node v18.6.0 _**`latest`**_ (see #53)

### CODE REVIEW

**Comment by iambumblehead** [comment]
@Swivelgames should this be merged?

**Comment by Swivelgames** [comment]
@iambumblehead If you're OK with the changes here, go for it!

**Comment by iambumblehead** [comment]
ok if you think a package-lock should be added, it could be added in a separate MR.

three thoughts about the package-lock,

 1. adding the package-lock would probably improve npm search ranking
 2. the package-lock is only useful for 'devDependencies' and therefore doesn't seem truly necessary
 3. including package-lock triggers the github PR bot for out-of-date and security-flagged packages. imo this an un-necessary nuisance

**Comment by Swivelgames** [comment]
All good points. Especially the last one related to `dependabot`. I'm curious if we can disable it.

**Comment by iambumblehead** [comment]
@Swivelgames small thing `encodeURI( url )` might be better than whitespace regexp here https://github.com/iambumblehead/esmock/pull/59/files#diff-5ceb3045b8c7bae26ef7e990191195692449d3b4b70219589b193473642260f6R87

**Pull request merged**
