### PR TITLE
do not error when processing sources that include node hashbang

### PR DESCRIPTION
**Pull request by iambumblehead**
cc @koshic  @tommy-mitchell re https://github.com/iambumblehead/esmock/issues/215

this PR removes the hashbang line from the sources before prepending import expressions, then re-adds any hashbang line to the final result returned by the loader

### CODE REVIEW

**Comment by iambumblehead** [comment]
@tommy-mitchell thank you for giving esmock your valuable attention. Feel free to leave any comments or advice.

This PR builds on the test from your earlier PR

**Comment by iambumblehead** [comment]
this test is failing in windows and maybe a different PR should resolve it. It relates to filesystem paths

    "test-metaresolve": "rimraf dist && tsc && cross-env \"NODE_OPTIONS=--experimental-import-meta-resolve --loader=esmock\" NODE_NO_WARNINGS=1 ava",

**Comment by iambumblehead** [comment]
the win32 could probably be resolved soon, but slow internet speeds here make it difficult to setup a windows virtual machine to run tests with latest node 18

**Comment by tommy-mitchell** [comment]
I have a Windows x64 machine, would that work for reproducing? I could try resolving it

**Comment by iambumblehead** [comment]
@tommy-mitchell that would be great. [Here is where](https://github.com/iambumblehead/esmock/blob/master/src/esmockModule.js#L26) I _think_ the problem is. I think import.meta.resolve is returning the path n the wrong format
```javascript
const resolve = isMetaResolve ?
  (import.meta.resolve.constructor.name === 'AsyncFunction'
    ? async (id, p) => import.meta.resolve(id, asFileURL(p))
      .catch(() => resolvewith(id, p))
    : (id, p) => {
      try { return import.meta.resolve(id, asFileURL(p)) }
      catch { return resolvewith(id, p) }
    })
  : resolvewith
```

cd into the tests-source-map folder and `npm install` then `npm test` to run the tests

**Comment by iambumblehead** [comment]
Maybe we should _only support_ the async variant of import.meta.resolve, eg node 20+ and fallback to resolvewith for every other case. Any solution you recommend is good too

**Comment by iambumblehead** [comment]
possibly related https://github.com/nodejs/node/issues/35518

Screen Shot 2023-07-27 at 8 43 19 PM

**Comment by iambumblehead** [comment]
Pinning the node version number to 18.16 resolved the pipeline error. A ticket for that node 18.17 issue is created here https://github.com/nodejs/node/issues/48948 and so this PR for hashbang support is complete and ready for review

**Comment by iambumblehead** [comment]
if anyone has retro-active review comments feel free to leave those

**Pull request merged**
