### PR TITLE
add jest+typescript test

### PR DESCRIPTION
**Pull request by iambumblehead**
@cyberwombat either "tsm" or "ts-node" could be used the same way here, but this PR uses --loader=tsm now.

re https://github.com/iambumblehead/esmock/issues/154

### CODE REVIEW

**Comment by iambumblehead** [comment]
@cyberwombat would this type of test setup work for your tests?

**Comment by cyberwombat** [comment]
I should be able to use tsm - right now I use ts-jest transform. Ive never used tsm as a loader but happy to experiment.

**Comment by iambumblehead** [comment]
I did not know about ts-jest transform... I'm interested to change this PR to use the ts-jest transform

**Comment by cyberwombat** [comment]
Ya my jest.config.ts looks like this:
```
export default {
  testEnvironment: 'jest-environment-node',
  setupFiles: ['./test/setup.ts'],
  setupFilesAfterEnv: ['./test/bootstrap.ts'],
  transform: {
    '^.+\\.tsx?$': [
      'ts-jest',
      {
        useESM: true,
        diagnostics: false,
        compilerHost: true,
        incremental: true
      }
    ]
  },
  moduleNameMapper: {
    '^(\\.{1,2}/.*)\\.js$': '$1',
    '^lib/(.*)$': 'src/lib/$1',
   ...
  },
  extensionsToTreatAsEsm: ['.ts'],
  testPathIgnorePatterns: ['<rootDir>/dist', '.history'],
  modulePaths: ['<rootDir>/src', '<rootDir>/test', '<rootDir>'],
  preset: 'ts-jest'
}

```

**Comment by iambumblehead** [comment]
Actually, based on my admittedly limited understanding of jest... probably jest transform will not work. I think the ts transformation must occur through a --loader like tsm or ts-node. I can try to use the jest.config.ts provided but I don't believe I will succeed.

**Comment by cyberwombat** [comment]
I am not attached - I do want to be able to use TS files for my `setupFiles` and `setupFilesAfterEnv` however as these reference common TS libs in main code. I will try using tsm instead tomorrow and see what happens in general.

**Comment by iambumblehead** [comment]
jest tries to use ts-node, so updating this PR to use ts-node rather than tsm seems like a good idea.

when using the jest.config.ts, errors like these occur...
```console
Error: Jest: Failed to parse the TypeScript config file /home/bumble/software/esmock/tests/tests-jest-ts/jest.config.ts
  Error: Must use import to load ES Module: /home/bumble/software/esmock/tests/tests-jest-ts/jest.config.ts
require() of ES modules is not supported.
require() of /home/bumble/software/esmock/tests/tests-jest-ts/jest.config.ts from /home/bumble/software/esmock/tests/tests-jest-ts/node_modules/jest-config/build/readConfigFileAndSetRootDir.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /home/bumble/software/esmock/tests/tests-jest-ts/package.json.
```

**Comment by cyberwombat** [comment]
Hmm. I can't tell if its struggling with a TS config or just the ESM. I think the latter. What I did is have "type": "module" in my `package.json` and use this for my `tsconfig.json`:
````
{
  "extends": "@tsconfig/node14/tsconfig.json",
  "compilerOptions": {
    "useUnknownInCatchVariables": false,
    "target": "es2020",
    "lib": ["es2020"],
    "module": "esnext",
    "moduleResolution": "Node",
    "esModuleInterop": true, // Eases ESM support
    "types": ["node"],
    "allowSyntheticDefaultImports": true,
    "declaration": true,
    "strict": true,
    "strictNullChecks": true,
    "alwaysStrict": true,
    "incremental": true,
    "noImplicitReturns": false,
    "noImplicitThis": false,
    "noUnusedLocals": false,
    "noUnusedParameters": false,
    "noEmit": true,
    "noFallthroughCasesInSwitch": false,
    "inlineSourceMap": true,
    "inlineSources": true,
    "experimentalDecorators": true,
    "strictPropertyInitialization": false,
    "resolveJsonModule": true,
    "outDir": "dist",
    "baseUrl": ".",
    "paths": {
  
    },
    "typeRoots": [
      "node_modules/@types",
      "typings"
      //"node_modules/graphql/type/schema.d.ts",
    ],
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
````

**Comment by cyberwombat** [comment]
Once think I wanted to avoid is doing all imports with 'js' extensions as that makes a total mess for jest/ts-jest. Also I had to play around to have VSCode Inteliisense play nice so these settings are the result of that.

**Comment by iambumblehead** [comment]
I haven't succeeded in replacing tsm with ts-jest :/

**Comment by cyberwombat** [comment]
What about ts-node? From reading comments here and there it seems to have a better overall support w Jest and has native esm loader https://www.npmjs.com/package/ts-node

**Comment by iambumblehead** [comment]
when tsm is replaced with ts-node/esm, this happens when the tests run,
```console
 FAIL  ./esmock.node-jest.test.ts
  ● Test suite failed to run

    thrown: Object {

        "diagnosticCodes": Array [
          2593,
          2304,
        ],
      }
```

**Comment by iambumblehead** [comment]
a ts-node/esm test folder with passing esmock tests is here https://github.com/iambumblehead/esmock/tree/master/tests/tests-nodets this error appears to occur specifically in combination with jest

**Comment by iambumblehead** [comment]
@cyberwombat the ts-node/esm test at this PR is passing. If you have time and would provide the favor of trying to add something like your jest.config.ts file to the PR that would be awesome. If we can support that file, we should include that with the test.

**Comment by iambumblehead** [comment]
let's merge this now, in order to update the wiki with links to this test-jest-ts folder. A separate PR could be used for any subsequent changes

**Comment by cyberwombat** [comment]
I am having no luck w `jest-light-runner`. I was not able to run directly from repo (too many links/globals I could not match) but have same scenario on my own code.

**Comment by iambumblehead** [comment]
ok thanks for helping me to this point

**Comment by cyberwombat** [comment]
Frankly the solution is probably to dump Jest. It's pretty outdated these days and they've expressed a lack of motivation in supporting ESM mocks. I'm exploring [vitest](https://vitest.dev/) to see if that has better options. It supports TS and ESM natively which is nice. Thank you for your effort

**Comment by iambumblehead** [comment]
I would be interested to know what you think of vitest, as there are many positive reviews

**Pull request merged**
