### PR TITLE
added workspace test

### PR DESCRIPTION
**Pull request by iambumblehead**
closes https://github.com/iambumblehead/esmock/issues/235

The new branch uses an updated version of resolvewithplus and should do the following things,
 * when typescript is detected, should resolve moduleIds from things like { "main": "./index.js" }, where "index.ts" should be returned rather than "index.js",
 * when typescript is detected, should resolve moduleIds from things like "./local-file.js" where "./local-file.ts" should be returned rather than "./local-file.js"

### CODE REVIEW

**Comment by iambumblehead** [comment]
Configuring deeply nested test folders to use local "esmock.js" with "--loader" in both windows and linux test environments is overly difficult. It would be easier to start this feature after the initialize hook is merged https://github.com/iambumblehead/esmock/pull/240 so that "--loader" can be removed from these workspace tests.

**Comment by iambumblehead** [comment]
@koshic @tpluscode please review

**Comment by iambumblehead** [comment]
Merging, as these changes seem relatively low-risk. If issues around typescript resolution are reported, the resolver package could be reverted to the previous version.

**Comment by iambumblehead** [comment]
feel free to leave retro-active review, these changes are published to esmock@2.5.1

**Comment by tpluscode** [comment]
Well, most importantly, my project now works without any workarounds. Very nice. Thank you @iambumblehead!

**Comment by iambumblehead** [comment]
@tpluscode awesome thank you!

**Pull request merged**
